[build]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm ci && npm run build"
nixpacksPlan = { "providers" = ["python", "node"] }

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
multiRegionConfig = { "europe-west4-drams3a" = { "numReplicas" = 1 } }
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 