[build]
builder = "NIXPACKS"
nixpacksPlan = {"providers":["node","python"]}

[deploy]
startCommand = "chmod +x start.sh && ./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
runtime = "V2"
numReplicas = 1
sleepApplication = false
multiRegionConfig = {"europe-west4-drams3a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[envVars]]
name = "NODE_ENV"
value = "production"

[[envVars]]
name = "PYTHONUNBUFFERED"
value = "1"

[[envVars]]
name = "HOST"
value = "0.0.0.0"

[[envVars]]
name = "PYTHONPATH"
value = "/app:/app/backend"