[build]
builder = "NIXPACKS"
buildCommand = "cd frontend && npm install && npm run build && cd .. && ls -la frontend/ && ls -la frontend/dist/ && rm -rf backend/static && mkdir -p backend/static && cp -r frontend/dist/* backend/static/ && ls -la backend/static/"
nixpacksPlan = { "providers" = ["python", "node"] }

[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
multiRegionConfig = { "europe-west4-drams3a" = { "numReplicas" = 1 } }
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT" 